apiVersion: cloud-build-notifiers/v1
kind: SlackNotifier
metadata:
  name: cloud-build-slack-notifications
spec:
  notification:
    filter: build.status in [Build.Status.WORKING, Build.Status.SUCCESS, Build.Status.FAILURE, Build.Status.TIMEOUT, Build.Status.INTERNAL_ERROR, Build.Status.CANCELLED, Build.Status.EXPIRED]
    params:
      buildStatus: $(build.status)
    delivery:
      webhookUrl:
        secretRef: webhook-url
    template:
      type: golang
      uri: ${notif_template_url}
  secrets:
  - name: webhook-url
    value: ${slack_app_webhook_url}
